language: android

env:
  global:
    - MALLOC_ARENA_MAX=2
    - TERM=dumb
    - ADB_INSTALL_TIMEOUT=12

jdk: oraclejdk7

android:
  components:
    - build-tools-23.0.1
    - android-23
    - android-22

script:
    - ./gradlew testBlueDebugUnitTestCoverage
