language: android

env:
  global:
    - MALLOC_ARENA_MAX=2
    - TERM=dumb
    - ADB_INSTALL_TIMEOUT=12

jdk: oraclejdk7

android:
  components:
    - build-tools-23.0.1
    - android-23
    - android-19
    - addon-google_apis-google-21
    - addon-google_apis-google-19

before_script:
    - echo no | android create avd --skin WXGA800 --force -n test -t "Google Inc.:Google APIs:19"
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - ./gradlew testBlueDebugUnitTestCoverage
